# .github/workflows/deploy.yml

name: Deploy to GitHub

on:
  # push:
  #   branches:
  #     - master
  #     - main

  workflow_dispatch:  # Permite execução manual

jobs:
  build_and_deploy:
    uses: ./.github/workflows/reusable-build.yml  # Chama o workflow reutilizável

  deploy:
    needs: build_and_deploy  # Aguarda o job de build_and_deploy completar

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5


#Este ajuste permite que o deploy ocorra tanto em um evento de push quanto quando o fluxo de trabalho é disparado manualmente ( workflow_dispatch).
      - name: Deploy to GitHub Pages 🚀
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}  # Deploy em push ou execução manual
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
