# .github/workflows/deploy.yml

name: Build and Deploy Web

on:
  # Pode ser ativado por push ou manualmente
  # push:
  #   branches:
  #     - master
  #     - main
  workflow_dispatch:  # Permite execução manual

jobs:
  build_and_upload:
    uses: ./.github/workflows/reusable-build.yml  # Chama o workflow reutilizável

    steps:
      - name: Flet Build Web
        run: |
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}, USER: ${GITHUB_REPOSITORY%/*}, PROJECT_BASE_URL: ${GITHUB_REPOSITORY#*/}"
          flutter config --no-analytics
          flet build web --base-url ${GITHUB_REPOSITORY#*/} --route-url-strategy hash

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web-build-artifact
          path: build/web
