# .github/workflows/reusable-build.yml

name: Reusable Build and Deploy to GitHub Pages

on:
  workflow_call:  # Torna o workflow reutilizável por outros workflows

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.6
  FLUTTER_VERSION: 3.24
  
jobs:
  build:
    runs-on: windows-latest

    steps: 
    # Baixa o código-fonte do repositório no ambiente de execução
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Instalação do Python na versão desejada
    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    # Instalação das dependências Python
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U -r requirements.txt

    # Instalação do Flutter na versão desejada
    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    # Build do projeto web usando o Flet
    - name: Flet Build Web
      run: |
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}, USER: ${GITHUB_REPOSITORY%/*}, PROJECT_BASE_URL: ${GITHUB_REPOSITORY#*/}"
        flutter config --no-analytics
        flet build web --base-url ${GITHUB_REPOSITORY#*/} --route-url-strategy hash
