name: Reusable Build and Deploy to GitHub Pages

on:
  workflow_call:  # Torna o workflow reutilizável por outros workflows

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.6
  FLUTTER_VERSION: 3.24

jobs:
  build:
    runs-on: windows-latest

    steps: 
    # Baixa o código-fonte do repositório no ambiente de execução
    - name: Checkout code
      uses: actions/checkout@v4

    # Cache para dependências Python (evita reinstalar sempre)
    - name: Cache Python Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip  # Caminho onde o pip armazena pacotes
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # Instalação do Python na versão desejada
    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # Instalação das dependências Python, se não estiverem no cache
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U -r requirements.txt

    # Cache para Flutter SDK
    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache  # Caminho onde o Flutter armazena dependências
        key: flutter-${{ env.FLUTTER_VERSION }}
        restore-keys: |
          flutter-

    # Instalação do Flutter na versão desejada, se não estiver no cache
    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
